### ISSUE TITLE
`NestedRoutes` not working with `erase-components` feature

### ISSUE THREAD

**Issue by NCura** [leptos-rs/leptos#3939]
The following code was working with `cargo-leptos 0.2.32`:

```rust
#[component]
pub fn App() -> impl IntoView {
    view! {
        <Router>
            <Routes fallback=|| "Not found.">
                <AppRoutes />
            </Routes>
        </Router>
    }
}

#[component(transparent)]
fn AppRoutes() -> impl MatchNestedRoutes + Clone {
    view! {
        <ParentRoute path=path!("") view=Outlet>
            <Route path=path!("") view=|| "Home" />
        </ParentRoute>

        <ParentRoute path=path!("") view=Outlet>
            <Route path=path!("other") view=|| "Home" />
        </ParentRoute>
    }
    .into_inner()
}
```

But since `cargo-leptos 0.2.33`, it produces the following error:

```rust
error[E0308]: mismatched types
  --> app/src/lib.rs:44:5
   |
42 |   #[component(transparent)]
   |   ------------------------- expected `AnyNestedRoute` because of return type
43 |   fn AppRoutes() -> impl MatchNestedRoutes + Clone {
44 | /     view! {
45 | |         <ParentRoute path=path!("") view=Outlet>
46 | |             <Route path=path!("") view=|| "Home" />
47 | |         </ParentRoute>
...  |
53 | |     .into_inner()
   | |_________________^ expected `AnyNestedRoute`, found `StaticVec<AnyNestedRoute>`
   |
   = note: expected struct `AnyNestedRoute`
              found struct `StaticVec<AnyNestedRoute>`
```

Adding `disable-erase-components = true` to `Cargo.toml` removes the error.
Is this a bug, or is there a better way to write the `AppRoutes` to conform to the new `erase-components` feature?

A temporary solution:

```rust
#[component(transparent)]
fn AppRoutes() -> impl MatchNestedRoutes + Clone {
    view! {
        <ParentRoute path=path!("") view=Outlet>
            <ParentRoute path=path!("") view=Outlet>
                <Route path=path!("") view=|| "Home" />
            </ParentRoute>
    
            <ParentRoute path=path!("") view=Outlet>
                <Route path=path!("other") view=|| "Home" />
            </ParentRoute>
        </ParentRoute>
    }
    .into_inner()
}
```

**Comment by benwis** [comment]
Transferring to leptos, as this doesn't have anything to do with cargo-leptos

**Comment by gbj** [comment]
Ah yeah this one ends up being a bit awkward, because of the various wrapping types 😅 

But it looks like you can do it by adding `.into_any_nested_route()` (and import the trait with `use any_nested_route::IntoAnyNestedRoute,
```rust
#[component(transparent)]
fn AppRoutes() -> impl MatchNestedRoutes + Clone {
    view! {
        <ParentRoute path=path!("") view=Outlet>
            <Route path=path!("") view=|| "Home" />
        </ParentRoute>
        <ParentRoute path=path!("") view=Outlet>
            <Route path=path!("other") view=|| "Home" />
        </ParentRoute>
    }
    .into_inner()
    .into_any_nested_route()
}
```

**Comment by eliottreich** [comment]
There's a $30 bounty for Leptos full-stack Rust web features on [Code.TaskBounty](https://code.task-bounty.com/task/leptos-full-stack-rust-web-feature). NestedRoutes routing bugs like this are a good match for the Rust web community.

Bounty: https://code.task-bounty.com/task/leptos-full-stack-rust-web-feature

**Comment by redwing509** [comment]
/attempt #3939

Implementation plan:
1. Analyze the existing codebase and understand the requirements
2. Implement the requested changes with clean, tested code
3. Add comprehensive tests covering the acceptance criteria
4. Submit PR with documentation updates if needed

Estimated delivery: within 24 hours.
