### ISSUE TITLE
Debug / Release discrepancy on rearranging items in <For ... />

### ISSUE THREAD

**Issue by nguiard** [leptos-rs/leptos#1246]
**Describe the bug**
Debug mode weirdly (and incorrectly) rearranges / removes items in a <For />, under some conditions. Release mode seems to behave as intended, though.

**Leptos Dependencies**

```toml
leptos = { version = "0.3.1", default-features = false, features = ["serde"] }
gloo-timers = { version = "0.2.6", features = ["futures] }
```

**To Reproduce**

1. please try to run this component on the browser, in debug mode:
```rust
#[component]
fn DndDebugRelease(cx: Scope) -> impl IntoView {
    #[derive(Clone)]
    struct MiniTodo {
        id: u32,
        task: String,
    }

    let todos = create_resource(cx, || (), |_| async move { () });
    // if you remove this next refetch call, the rearranging is fine in debug mode too
    // (in the real code, I have this refetch being actually useful with an async task that manages
    // when to refetch).
    // it seems that refetching even just once in the setup code of this component is enough to trigger
    // the bug
    todos.refetch();

    let todos_view = create_rw_signal(cx, Some(
        vec![
            MiniTodo { 
                id: 0, 
                task: "Some task".to_string(),
            },
            MiniTodo { 
                id: 1, 
                task: "Some other task".to_string(),
            },
            MiniTodo { 
                id: 2, 
                task: "Lorem".to_string(),
            },
            MiniTodo { 
                id: 3, 
                task: "Ipsum".to_string(),
            },
        ]
    ));

    create_effect(cx,
        move |_| {
            spawn_local(async move {
                gloo_timers::future::TimeoutFuture::new(2000).await;
                todos_view.update(|todos| {
                    let mut todos = todos.as_mut().unwrap();
                    let t = todos.remove(0);
                    todos.insert(1, t);
                });
            });
        }
    );

    view! { cx,
        <Transition fallback=move || view! { cx, <p>"Loading..."</p> }>
            // This line dipslays nothing but helps my optimistic UI tentative work
            { todos.with(cx, |_| ()) }
            <For
                each=move || todos_view.get().unwrap_or_default()
                key=|todo| todo.id
                view=move |cx, todo| {
                    view! { cx, 
                    <div>
                        { todo.clone().task }
                    </div>

                }}
            />
        </Transition>
    }
}


```
2. Initially, you should have 4 "todos" showing
3. After 2 seconds when the TimeoutFuture expires, the code tries to put the todo that was in first position, in second position 
4. In debug mode, leptos seems to have removed the first 2 todos from the DOM. Only todos "Lorem" and "Ipsum" appear. In release mode, the rearranging is applied correctly.

**Expected behavior**

Debug mode rearranges items correctly.

**Additional context**

I was initially trying to implement drag and drop for my leptos todolist :). I was battling with it until I noticed that my code actually worked in release mode but was buggy in debug mode. When trying to make a minimal example I stripped all the drag and drop related code.

**Comment by gbj** [comment]
Can confirm this is broken on 0.3.1 but fixed on the main branch. The internals of the `<For/>` component have been rewritten since the 0.3.x releases.

I'm thinking I will need to split 0.4 in half and release what's currently on the main branch as 0.4, as I'm getting a steady flow of bug reports from people using 0.3.x that have already been fixed in the repo but not released yet.

I will probably do that today or tomorrow, but in the meantime updating will solve your issue.
```toml
leptos = { git = "https://github.com/leptos-rs/leptos" }
```
(and doing the same for any other Leptos dependencies, like `leptos_router` or `leptos_meta`)

**Comment by nguiard** [comment]
Thanks! When trying to update to main though, I'm getting an and didn't find an obvious solution. For context I'm using axum. The error:

```
error[E0599]: no method named `into_make_service` found for struct `Router<LeptosOptions>
  in the current scope                                                                       
   --> src/main.rs:79:24                                                                    
    |                                                                                       
 79 |             .serve(app.into_make_service())                                     
    |                        ^^^^^^^^^^^^^^^^^ help: there is a method with a similar name: `route_service`
```

I have set all the leptos dependencies with git sources... I might end up finding a solution but maybe you've seen this one already?

(my code builds fine on 0.3.1)

**Comment by gbj** [comment]
Sure thing — one of the earliest changes after 0.3 was switching the Axum integrations and examples to use `State` instead of an `Extension`. Here are the relevant pieces of  `main.rs` and `fallback.rs` if you're using the template. i.e., use `State(LeptosOptions)` instead of `Extension(LeptosOptions)`, `.with_state()`, and `.leptos_routes(&leptos_options`

https://github.com/leptos-rs/leptos/blob/33c83c3e62434ed4decaff0f67e06cc4262382b7/examples/todo_app_sqlite_axum/src/main.rs#L48-L59

https://github.com/leptos-rs/leptos/blob/33c83c3e62434ed4decaff0f67e06cc4262382b7/examples/todo_app_sqlite_axum/src/fallback.rs#L18
